CREATE TABLE IF NOT EXISTS platforms(
    id BIGINT AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    name varchar(50) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at BIGINT NULL DEFAULT 0,
    CONSTRAINT kbr_platforms_pk PRIMARY KEY(id)
);g